#!/usr/bin/env python3

"""
Test script for the new 835 export system with AWS S3 storage
"""

import requests
import json
from typing import Dict, Any

BASE_URL = "http://localhost:8001"

def test_generate_835_export():
    """Test generating a 835 export with new table structure"""
    
    # You'll need a valid claim_id from your database
    test_claim_id = "test-claim-id"  # Replace with actual claim ID
    
    url = f"{BASE_URL}/generate-835/"
    
    payload = {
        "claim_id": test_claim_id,
        "org_id": "test-org-123",
        "generated_by": "user-123"
    }
    
    print(f"🧪 Testing 835 export generation...")
    print(f"URL: {url}")
    print(f"Payload: {json.dumps(payload, indent=2)}")
    
    try:
        response = requests.post(url, json=payload)
        
        print(f"\n📊 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            data = response.json()
            print(f"✅ Success! Export generated:")
            print(f"   Export ID: {data.get('export_id')}")
            print(f"   Reference: {data.get('export_reference')}")
            print(f"   S3 Path: {data.get('s3_path')}")
            print(f"   File Size: {data.get('file_size_kb')} KB")
            print(f"   Status: {data.get('status')}")
            
            return data.get('export_id')
        else:
            print(f"❌ Error: {response.text}")
            return None
            
    except Exception as e:
        print(f"❌ Request failed: {e}")
        return None

def test_list_exports():
    """Test listing all exports"""
    
    url = f"{BASE_URL}/generate-835/exports"
    
    print(f"\n🧪 Testing export listing...")
    print(f"URL: {url}")
    
    try:
        response = requests.get(url)
        
        print(f"\n📊 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            data = response.json()
            print(f"✅ Success! Found {len(data)} exports:")
            
            for export in data[:3]:  # Show first 3
                print(f"   Export ID: {export.get('export_id')}")
                print(f"   Reference: {export.get('export_reference')}")
                print(f"   Status: {export.get('status')}")
                print(f"   Claim: {export.get('claim_number')}")
                print(f"   Generated: {export.get('generated_at')}")
                print("   ---")
                
        else:
            print(f"❌ Error: {response.text}")
            
    except Exception as e:
        print(f"❌ Request failed: {e}")

def test_get_export_by_id(export_id: str):
    """Test getting specific export"""
    
    if not export_id:
        print("⚠️ No export ID provided, skipping test")
        return
    
    url = f"{BASE_URL}/generate-835/exports/{export_id}"
    
    print(f"\n🧪 Testing export retrieval...")
    print(f"URL: {url}")
    
    try:
        response = requests.get(url)
        
        print(f"\n📊 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            data = response.json()
            print(f"✅ Success! Export details:")
            print(f"   Export ID: {data.get('export_id')}")
            print(f"   Reference: {data.get('export_reference')}")
            print(f"   S3 Path: {data.get('storage_path')}")
            print(f"   Status: {data.get('status')}")
            print(f"   Claim ID: {data.get('claim_id')}")
            print(f"   Generated By: {data.get('generated_by')}")
            
        else:
            print(f"❌ Error: {response.text}")
            
    except Exception as e:
        print(f"❌ Request failed: {e}")

def test_download_export(export_id: str):
    """Test downloading export (generates presigned URL)"""
    
    if not export_id:
        print("⚠️ No export ID provided, skipping test")
        return
    
    url = f"{BASE_URL}/generate-835/exports/{export_id}/download"
    
    print(f"\n🧪 Testing export download...")
    print(f"URL: {url}")
    
    try:
        response = requests.post(url)
        
        print(f"\n📊 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            data = response.json()
            print(f"✅ Success! Download info:")
            print(f"   S3 Path: {data.get('s3_path')}")
            print(f"   Download URL: {data.get('download_url')[:100]}...")  # Truncate for display
            print(f"   Expires In: {data.get('expires_in_seconds')} seconds")
            
        else:
            print(f"❌ Error: {response.text}")
            
    except Exception as e:
        print(f"❌ Request failed: {e}")

def main():
    """Run all tests"""
    
    print("🚀 Starting 835 Export System Tests")
    print("=" * 50)
    
    # Test 1: Generate new export
    export_id = test_generate_835_export()
    
    # Test 2: List all exports
    test_list_exports()
    
    # Test 3: Get specific export
    test_get_export_by_id(export_id)
    
    # Test 4: Download export
    test_download_export(export_id)
    
    print("\n" + "=" * 50)
    print("🏁 Tests completed!")
    
    if export_id:
        print(f"\n💡 Generated Export ID for further testing: {export_id}")
    
    print("\n📋 New Table Structure Summary:")
    print("   - exports_835: Main export records with S3 paths")
    print("   - export_items: Links exports to claims/payments")
    print("   - Files stored in AWS S3 with presigned URL downloads")

if __name__ == "__main__":
    main()