#!/usr/bin/env python3

"""
Test the simplified 835 generation request (claim_id only)
"""

import requests
import json

def test_simplified_request():
    """Test the exact request format the user wants"""
    
    url = "http://localhost:8001/generate-835/"
    
    # User's exact requested format
    payload = {
        "claim_id": "03d3e06b-2dbc-4eb5-8055-c8e28d10d266"
    }
    
    print("🎯 Testing Simplified 835 Generation Request")
    print("=" * 50)
    print(f"URL: {url}")
    print(f"Payload: {json.dumps(payload, indent=2)}")
    print(f"Method: POST")
    
    try:
        response = requests.post(url, json=payload, timeout=30)
        
        print(f"\n📊 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            data = response.json()
            
            print(f"\n✅ SUCCESS!")
            print("=" * 30)
            print(f"Export ID: {data.get('export_id')}")
            print(f"Export Reference: {data.get('export_reference')}")
            print(f"File Name: {data.get('file_name')}")
            print(f"S3 Path: {data.get('s3_path')}")
            print(f"Claim Number: {data.get('claim_number')}")
            print(f"Total Amount: ${data.get('total_amount')}")
            print(f"Status: {data.get('status')}")
            print(f"Generated At: {data.get('generated_at')}")
            
            # Verify defaults were used
            print(f"\n🔍 Default Values Used:")
            print(f"Org ID: Used default UUID")
            print(f"Generated By: Used default (None)")
            
            return True
            
        elif response.status_code == 422:
            print(f"\n❌ Validation Error:")
            error_data = response.json()
            print(json.dumps(error_data, indent=2))
            return False
            
        else:
            print(f"\n❌ Error {response.status_code}:")
            try:
                error_data = response.json()
                print(json.dumps(error_data, indent=2))
            except:
                print(response.text)
            return False
            
    except requests.exceptions.ConnectionError:
        print(f"\n❌ Connection Error: Server not running")
        print(f"Start server with: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001")
        return False
        
    except Exception as e:
        print(f"\n❌ Request failed: {e}")
        return False

def show_curl_examples():
    """Show different ways to use the API"""
    
    print(f"\n📋 API Usage Examples")
    print("=" * 40)
    
    print(f"\n1️⃣ Minimal Request (Your Format):")
    print(f"""curl -X POST "http://localhost:8001/generate-835/" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "claim_id": "03d3e06b-2dbc-4eb5-8055-c8e28d10d266"
  }}'""")
    
    print(f"\n2️⃣ With Organization ID:")
    print(f"""curl -X POST "http://localhost:8001/generate-835/" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "claim_id": "03d3e06b-2dbc-4eb5-8055-c8e28d10d266",
    "org_id": "123e4567-e89b-12d3-a456-426614174000"
  }}'""")
    
    print(f"\n3️⃣ Full Request:")
    print(f"""curl -X POST "http://localhost:8001/generate-835/" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "claim_id": "03d3e06b-2dbc-4eb5-8055-c8e28d10d266",
    "org_id": "123e4567-e89b-12d3-a456-426614174000",
    "generated_by": "456e7890-e89b-12d3-a456-426614174001"
  }}'""")

def main():
    print("🚀 Simplified 835 Generation Test")
    print("Testing the exact request format you want")
    print("=" * 60)
    
    success = test_simplified_request()
    
    show_curl_examples()
    
    print(f"\n" + "=" * 60)
    if success:
        print("🎉 Your simplified request format works perfectly!")
        print("✅ Only claim_id is required")
        print("✅ org_id and generated_by are optional")
        print("✅ File is named with claim number")
        print("✅ File is stored in S3 with organized structure")
    else:
        print("⚠️ Make sure the server is running on port 8001")
        print("Command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001")

if __name__ == "__main__":
    main()